package com.mrjaffesclass.apcs.mvc.template;
import com.mrjaffesclass.apcs.messenger.*;
import java.util.Scanner;
/**
 * MVC Template
 * This is a template of an MVC framework used by APCS for the 
 * LandMine project (and others)
 * @author Roger Jaffe
 * @version 1.0
 * 
 */
public class View extends javax.swing.JFrame implements MessageHandler {

    double age1;
    int age;
    
  private final Messenger mvcMessaging;
  
  /**
   * Creates a new view
   * @param messages mvcMessaging object
   */
  public View(Messenger messages) {
    mvcMessaging = messages;   // Save the calling controller instance
    initComponents();           // Create and init the GUI components
  }
  
  /**
   * Initialize the model here and subscribe
   * to any required messages
   */
  public void init() {
    // Subscribe to messages here
    mvcMessaging.subscribe("model:minAgeChanged", this); //listens for the minimum age
    mvcMessaging.subscribe("model:noPermissableDating", this); //listens for inibility to date
    mvcMessaging.subscribe("model:maxAgeChanged", this); //listens for the maximum age
    mvcMessaging.subscribe("model:False", this); //for unreasonable values
  }
  
  @Override
  public void messageHandler(String messageName, Object messagePayload) {
    if (messagePayload != null) {
      System.out.println("MSG: received by view: "+messageName+" | "+messagePayload.toString());
    } else {
      System.out.println("MSG: received by view: "+messageName+" | No data sent");
    }
    if (messageName.equals("model:minAgeChanged")) {
      minAgeOut.setText("Minimum Dating Age: " + messagePayload.toString());;
    } 
    if (messageName.equals("model:maxAgeChanged")) {
        maxAgeOut.setText("Maximum Dating Age: " + messagePayload.toString());
    }
    if (messageName.equals("model:noPermissableDating")) {
        minAgeOut.setText("Not a dating age");
        maxAgeOut.setText("Not a dating age");
    }
    if (messageName.equals("model:False")) {//no one is negative years old or more than 130
        minAgeOut.setText("False statement");
        maxAgeOut.setText("False Statement");
    }
  }

  /**
   * Instantiate an object with the age that was inputted
   * @param direction delivery, the number being delivered
   */
  private MessagePayload createPayload(int delivery) {
    MessagePayload payload = new MessagePayload(delivery);
    return payload;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        askingAge = new javax.swing.JLabel();
        askingAgeIn = new javax.swing.JTextField();
        minAgeOut = new javax.swing.JLabel();
        maxAgeOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        askingAge.setText("What is your age?");

        askingAgeIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                askingAgeInActionPerformed(evt);
            }
        });

        minAgeOut.setText("Minimum Permissable Age");

        maxAgeOut.setText("Maximum Permissable Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(minAgeOut)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(askingAgeIn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxAgeOut))
                        .addGap(0, 69, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(askingAge)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(askingAge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(askingAgeIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(minAgeOut)
                .addGap(18, 18, 18)
                .addComponent(maxAgeOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* When the text for age is changed, notifies model with the new age
    */
    private void askingAgeInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_askingAgeInActionPerformed
        Scanner sb = new Scanner(askingAgeIn.getText());
        if (sb.hasNextDouble()) {
            age1 = sb.nextDouble();
        int age = (int) age1;
        mvcMessaging.notify("view:ageChanged", age);
        } else {
        minAgeOut.setText("No numbers were found");
        maxAgeOut.setText("Please write the age numerically");
        }
    }//GEN-LAST:event_askingAgeInActionPerformed

  /**
   * @param args the command line arguments
   */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel askingAge;
    private javax.swing.JTextField askingAgeIn;
    private javax.swing.JLabel maxAgeOut;
    private javax.swing.JLabel minAgeOut;
    // End of variables declaration//GEN-END:variables
}
